In [28]:
from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier

In [29]:
iris = load_iris() #carregamento do dataset
iris.keys() #exibe as chaves(colunas)

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

In [30]:
print(iris['DESCR'][:193] + '\n...') #Exibir a descrição do dataset

Iris Plants Database

Notes
-----
Data Set Characteristics:
    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive att
...


In [31]:
iris['feature_names'] #exibe o nome das caracteristicas usadas para classificação.

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [32]:
iris['target_names'] #exibe o nome das classificações

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [33]:
print(iris['data'].shape) #shape exibe o tamanho do dataset
iris['data'][:10] #exibe as 10 primeiras linhas

(150, 4)


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [43]:
iris['target'] #exibe a classificação das flores de acordo com os target_names
# 0 para setosa
# 1 para versicolar
# 2 para virginica

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [41]:
#criando o modelo de aprendizagem de maquina.
import numpy
knn = KNeighborsClassifier(n_neighbors = 3)
X = iris.data[:,:3] #as caracteristicas
y = iris.target #classificacao
#dados de treinamento 'até 40' de cada classe
xt = numpy.concatenate([X[:40,:], X[51:90,:], X[101:140,:]])
yt = numpy.concatenate([y[:40], y[51:90], y[101:140]])
knn.fit(xt,yt)

#validacão com o restante dos dados
xv = numpy.concatenate([X[40:50,:], X[90:100,:], X[140:150,:]])
yv = numpy.concatenate([y[40:50], y[90:100], y[140:150]])
yp = knn.predict(xv)

print(yp) #resultado encontrado
print(yv) #resultado esperado

[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 2 1 2 2 2 2 2 2 2 2]
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2]


In [42]:
#Precisão da predição
knn.score(xv, yv) #Teste em porcentage.

#alterar a quantidade de vizinhos (linha 3 do bloco anterior)
#alterar a quantidade de caracteristicas (linha 4 do bloco anterior)

0.9666666666666667